### ISSUE TITLE
Co-existing with other crates, e.g. sqlx

### ISSUE THREAD

**Issue by nyurik** [CGamesPlay/sqlite3_ext#1]
Is there a way to re-use just the extension functionality of this crate while relying on other crates like `sqlx` for the actual sqlite DB access?

I would like to add a few functions to sqlite, e.g. hashing like `md5(...)` and `sha256(...)`.  These functions should ideally be part of the single binary, which also includes the statically-linked sqlite (the extension functions themselves would likely be a separate crate, but the user of that crate may want to combine it all into a single binary).

I use sqlx to connect to sqlite, and ideally I want to be able to do build-time validation of queries that use those functions.  I am not certain if it is possible in sqlx (they have a special offline query validation tool that runs during macro expansion (?)) -- so not certain at what point sqlite extension would be loaded. But even if sqlx's `query!` macro cannot be used, I would still want to do all connection and pool management with sqlx, while relying on this lib to build extensions.

What path do you think would work for such sqlite extension work?

**Comment by CGamesPlay** [comment]
This should definitely be possible to do. This crate actually depends on [libsqlite3-sys](https://crates.io/crates/libsqlite3-sys) to do the linking, which is the same that [sqlx-sqlite uses](https://crates.io/crates/sqlx-sqlite/0.7.1/dependencies), so you shouldn't need to do any additional linking steps.

I would be in favor of adding some feature-gated glue code, similar to [with_rusqlite](https://github.com/CGamesPlay/sqlite3_ext/blob/main/src/with_rusqlite.rs), that gets the sqlite3 handle and wraps in in an appropriate Connection object.

I'm not sure about the offline query validation. If the validator is just using a hard-coded list of functions and tables, you could manually add your extension's additions to that list. If it actually performs validation of the queries against a live database, then it's theoretically possible to do this, by loading compiling your extension as a separate crate and then having the connection setup depend on the crate.

**Comment by nyurik** [comment]
@CGamesPlay thank you for all the info!  I wrote [sqlite-hashes](https://crates.io/crates/sqlite-hashes) crate for the static usacase using rusqlite, but I do hope that I can somehow support dynamic lib generation as well, e.g. with a feature flag of sorts.
